# Based on ESLint CSS's automated baseline update workflow
# https://github.com/eslint/css/pull/187
#
# Copyright OpenJS Foundation and other contributors, https://openjsf.org/
# Released under the Apache License 2.0:
# https://github.com/eslint/css/blob/main/LICENSE
#
name: Update baseline
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  update-baseline:
    permissions:
      contents: write
      pull-requests: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup

      - name: Update baseline packages
        run: |
          pnpm install -D mdn-data@latest web-features@latest

      - name: Generate baseline data
        run: pnpm run build:baseline

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          commit-message: "fix: update baseline data"
          title: "fix: update baseline data"
          branch: update-baseline-data
          branch-suffix: timestamp
          body: |
            Updates baseline data using the latest versions of mdn-data and web-features.

            This PR is autogenerated by the "Update Baseline" GitHub Action.
